version: "3.7"

services:
  signaling:
    build: signaling
    restart: always
    network_mode: host
    depends_on:
      - janus
      - coturn
      - nats
  janus:
    build: janus
    network_mode: host
    depends_on:
      - coturn
  coturn:
    build: coturn
    network_mode: host
  nats:
    build: nats
    network_mode: host